spring.application.name=${SPRING_APP_NAME:authserver}

spring.session.store-type=none

# check SecurityProperities.java for default user/pwd if not setting below values
# spring.security.user.name=user
# spring.security.user.password=password


# default jdbc configurations
spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:ss_default_jdbc}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${HIBERNATE_FORMAT_SQL:true}
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}

logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

