spring.application.name=${SPRING_APP_NAME:authserver}


# check SecurityProperities.java for default user/pwd if not setting below values
spring.security.user.name=user
spring.security.user.password=password


logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}

logging.pattern.console = ${LOGPATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

